<a href="https://colab.research.google.com/github/kim-woo-joon/AIproject/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD_%EA%B0%80%EC%9D%B4%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
from numpy.core.getlimits import array
array1 = np.array([1, 2, 3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array2 = np.array([[1, 2, 3], [2, 3, 4]])

print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array3 = np.array([[1, 2, 3]])

print('array3 type " ', type(array3))
print('array3 array 형태 : ', array3.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type "  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)


In [4]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
org_array = np.array([3, 1, 9, 5])
print('원본행렬 : ', org_array)
sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬 : ', sort_array1)
print('np.sort()호출 후 원본 행렬 : ', org_array)

sort_array2 = org_array.sort()

print('np.sort()호출 후 반환된 정렬 행렬 : ', sort_array2)
print('np.sort()호출 후 원본 행렬 : ', org_array)

원본행렬 :  [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort()호출 후 원본 행렬 :  [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬 :  None
np.sort()호출 후 원본 행렬 :  [1 3 5 9]


In [7]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 : ', sort_array1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [9]:
array2d = np.array([[8, 12], [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]
